### ISSUE TITLE
Operators in DLScript

### ISSUE THREAD

**Issue by bojidar-bg** [bojidar-bg/godot#12]
(suggested by @neikeq)

Would be nice to have things like `godot_vector2 godot_vector2_add(godot_vector2 a, godot_vector2 b)`

**Comment by karroffel** [comment]
Added basic operators for `String` and `Vector2` already, will do that for the rest of the core API too.

**Comment by karroffel** [comment]
For more complex types I added operators, idea is to have the biding implement the operator overloading behaviors in the target language itself.

Closing for now
